### PR TITLE
Set `fail-under=0` for interrogate

### PR DESCRIPTION
**Pull request by StevenMaude**
This is a temporary measure. Adding docstrings, particularly to the
domain specific language parts of the code, is a task to be completed
fairly soon, but not yet started.

For now, allow this check to run, but always pass. This avoids
inconveniencing developers who are doing other things right now. We
should enforce this again once docstrings are added to the relevant
parts of the code.

### CODE REVIEW

**Review by ghickman — CHANGES_REQUESTED** [review]
Can you also remove it from pre-commit, after some thought that's almost the bigger issue here.  Although doing this is still relevent so lets do both 🙂

**Comment by StevenMaude** [comment]
@ghickman: to clarify, you mean both of:

* `interrogate` shouldn't run in pre-commit at all for now, as opposed to what it does now: run and not complain
* we should leave the configuration existing in pyproject.toml

**Comment by ghickman** [comment]
@StevenMaude – yep, the more I think about it the more I don't think we want it in pre-commit at all because we don't plan to enforce docstrings everywhere (eg tests!), so I think it's just going to annoy us in pre-commit.

**Review by ghickman — APPROVED** [review]

**Comment by StevenMaude** [comment]
Updated!

**Pull request merged**
